#!/bin/bash

for file in `ls $1`
do
    strings -n 5 "$1/$file" |
    sed 's/^[ \t]*//g' |
    sed 's/[ \t]*$//g' |
    awk 'BEGIN { FS=RS } { print length, $0}' |
    sort +0n -1 |
    sed 's/^[0-9][0-9]* /'$file' /' > "$2/${file}.txt"
    head -n 5 "$2/${file}.txt" >> "$3"
#    sed -i 's/^.* //' "$2/${file}.txt"
done

