#!/bin/bash

# $1: dump path
# $2: extracted printable strings path
# $3: show file

for file in `ls $1`
do
    strings -n 5 "$1/$file" |
    # remove white space
    sed 's/^[ \t]*//g' |
    sed 's/[ \t]*$//g' | 
    awk 'length($0) >= 5 && length($0) <= 100' > "$2/${file}.txt"
    #awk 'BEGIN { FS=RS } { print length, $0}' |
    #sort +0n -1 |
    #sed 's/^[0-9][0-9]* /'$file' /' > "$2/${file}.txt"

    # find email string
    grep -P "[\w_-]+@[\w_-]+(\.[\w_-]+)+" "$2/${file}.txt" |
    # add file name
    sed 's/^/'$file' /g' |
    # remove timestamp
    sed 's/_[0-9,\.]* / /g' >> "$3"

    # find ip string
    #grep -P "([0-9]{1,3}\.){3}[0-9]{1,3}" "$2/${file}.txt" |
    #sed 's/^/'$file' /g' |
    #sed 's/_[0-9,\.]* / /g' >> "$3"

    # find domain string
    grep -P "^[\w][\w-]{0,62}(\.[\w][\w-]{0,62})+\.?" "$2/${file}.txt" |
    sed 's/^/'$file' /g' |
    sed 's/_[0-9,\.]* / /g' >> "$3"

    head -n 5 "$2/${file}.txt" |
    sed 's/^/'$file' /g' |
    sed 's/_[0-9,\.]* / /g' >> "$3"
done

